//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference5
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", ConfigurationName="ServiceReference5.LoanApplicationList_Port")]
    public interface LoanApplicationList_Port
    {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference5.Read_Result Read(ServiceReference5.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference5.Read_Result> ReadAsync(ServiceReference5.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference5.ReadByRecId_Result ReadByRecId(ServiceReference5.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference5.ReadByRecId_Result> ReadByRecIdAsync(ServiceReference5.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference5.ReadMultiple_Result ReadMultiple(ServiceReference5.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference5.ReadMultiple_Result> ReadMultipleAsync(ServiceReference5.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference5.IsUpdated_Result IsUpdated(ServiceReference5.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference5.IsUpdated_Result> IsUpdatedAsync(ServiceReference5.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference5.GetRecIdFromKey_Result GetRecIdFromKey(ServiceReference5.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference5.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ServiceReference5.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference5.Create_Result Create(ServiceReference5.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference5.Create_Result> CreateAsync(ServiceReference5.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference5.CreateMultiple_Result CreateMultiple(ServiceReference5.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference5.CreateMultiple_Result> CreateMultipleAsync(ServiceReference5.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference5.Update_Result Update(ServiceReference5.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference5.Update_Result> UpdateAsync(ServiceReference5.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference5.UpdateMultiple_Result UpdateMultiple(ServiceReference5.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/loanapplicationlist:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference5.UpdateMultiple_Result> UpdateMultipleAsync(ServiceReference5.UpdateMultiple request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist")]
    public partial class LoanApplicationList
    {
        
        private string keyField;
        
        private string loan_NoField;
        
        private System.DateTime application_DateField;
        
        private bool application_DateFieldSpecified;
        
        private string loan_Product_TypeField;
        
        private string loan_Product_Type_NameField;
        
        private string member_NoField;
        
        private string member_NameField;
        
        private decimal requested_AmountField;
        
        private bool requested_AmountFieldSpecified;
        
        private decimal approved_AmountField;
        
        private bool approved_AmountFieldSpecified;
        
        private decimal interestField;
        
        private bool interestFieldSpecified;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private string recIDField;
        
        private string captured_ByField;
        
        private string global_Dimension_1_CodeField;
        
        private string global_Dimension_2_CodeField;
        
        private string staff_NoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Loan_No
        {
            get
            {
                return this.loan_NoField;
            }
            set
            {
                this.loan_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime Application_Date
        {
            get
            {
                return this.application_DateField;
            }
            set
            {
                this.application_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Application_DateSpecified
        {
            get
            {
                return this.application_DateFieldSpecified;
            }
            set
            {
                this.application_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Loan_Product_Type
        {
            get
            {
                return this.loan_Product_TypeField;
            }
            set
            {
                this.loan_Product_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Loan_Product_Type_Name
        {
            get
            {
                return this.loan_Product_Type_NameField;
            }
            set
            {
                this.loan_Product_Type_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Member_No
        {
            get
            {
                return this.member_NoField;
            }
            set
            {
                this.member_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Member_Name
        {
            get
            {
                return this.member_NameField;
            }
            set
            {
                this.member_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Requested_Amount
        {
            get
            {
                return this.requested_AmountField;
            }
            set
            {
                this.requested_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Requested_AmountSpecified
        {
            get
            {
                return this.requested_AmountFieldSpecified;
            }
            set
            {
                this.requested_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal Approved_Amount
        {
            get
            {
                return this.approved_AmountField;
            }
            set
            {
                this.approved_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Approved_AmountSpecified
        {
            get
            {
                return this.approved_AmountFieldSpecified;
            }
            set
            {
                this.approved_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal Interest
        {
            get
            {
                return this.interestField;
            }
            set
            {
                this.interestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InterestSpecified
        {
            get
            {
                return this.interestFieldSpecified;
            }
            set
            {
                this.interestFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string RecID
        {
            get
            {
                return this.recIDField;
            }
            set
            {
                this.recIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Captured_By
        {
            get
            {
                return this.captured_ByField;
            }
            set
            {
                this.captured_ByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Global_Dimension_1_Code
        {
            get
            {
                return this.global_Dimension_1_CodeField;
            }
            set
            {
                this.global_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Global_Dimension_2_Code
        {
            get
            {
                return this.global_Dimension_2_CodeField;
            }
            set
            {
                this.global_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Staff_No
        {
            get
            {
                return this.staff_NoField;
            }
            set
            {
                this.staff_NoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist")]
    public enum Status
    {
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Rejected,
        
        /// <remarks/>
        Deffered,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist")]
    public partial class LoanApplicationList_Filter
    {
        
        private LoanApplicationList_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LoanApplicationList_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist")]
    public enum LoanApplicationList_Fields
    {
        
        /// <remarks/>
        Loan_No,
        
        /// <remarks/>
        Application_Date,
        
        /// <remarks/>
        Loan_Product_Type,
        
        /// <remarks/>
        Loan_Product_Type_Name,
        
        /// <remarks/>
        Member_No,
        
        /// <remarks/>
        Member_Name,
        
        /// <remarks/>
        Requested_Amount,
        
        /// <remarks/>
        Approved_Amount,
        
        /// <remarks/>
        Interest,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        RecID,
        
        /// <remarks/>
        Captured_By,
        
        /// <remarks/>
        Global_Dimension_1_Code,
        
        /// <remarks/>
        Global_Dimension_2_Code,
        
        /// <remarks/>
        Staff_No,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        public string Loan_No;
        
        public Read()
        {
        }
        
        public Read(string Loan_No)
        {
            this.Loan_No = Loan_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        public ServiceReference5.LoanApplicationList LoanApplicationList;
        
        public Read_Result()
        {
        }
        
        public Read_Result(ServiceReference5.LoanApplicationList LoanApplicationList)
        {
            this.LoanApplicationList = LoanApplicationList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        public ServiceReference5.LoanApplicationList LoanApplicationList;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(ServiceReference5.LoanApplicationList LoanApplicationList)
        {
            this.LoanApplicationList = LoanApplicationList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ServiceReference5.LoanApplicationList_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(ServiceReference5.LoanApplicationList_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference5.LoanApplicationList[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(ServiceReference5.LoanApplicationList[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        public ServiceReference5.LoanApplicationList LoanApplicationList;
        
        public Create()
        {
        }
        
        public Create(ServiceReference5.LoanApplicationList LoanApplicationList)
        {
            this.LoanApplicationList = LoanApplicationList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        public ServiceReference5.LoanApplicationList LoanApplicationList;
        
        public Create_Result()
        {
        }
        
        public Create_Result(ServiceReference5.LoanApplicationList LoanApplicationList)
        {
            this.LoanApplicationList = LoanApplicationList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference5.LoanApplicationList[] LoanApplicationList_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(ServiceReference5.LoanApplicationList[] LoanApplicationList_List)
        {
            this.LoanApplicationList_List = LoanApplicationList_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference5.LoanApplicationList[] LoanApplicationList_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(ServiceReference5.LoanApplicationList[] LoanApplicationList_List)
        {
            this.LoanApplicationList_List = LoanApplicationList_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        public ServiceReference5.LoanApplicationList LoanApplicationList;
        
        public Update()
        {
        }
        
        public Update(ServiceReference5.LoanApplicationList LoanApplicationList)
        {
            this.LoanApplicationList = LoanApplicationList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        public ServiceReference5.LoanApplicationList LoanApplicationList;
        
        public Update_Result()
        {
        }
        
        public Update_Result(ServiceReference5.LoanApplicationList LoanApplicationList)
        {
            this.LoanApplicationList = LoanApplicationList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference5.LoanApplicationList[] LoanApplicationList_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(ServiceReference5.LoanApplicationList[] LoanApplicationList_List)
        {
            this.LoanApplicationList_List = LoanApplicationList_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/loanapplicationlist", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference5.LoanApplicationList[] LoanApplicationList_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(ServiceReference5.LoanApplicationList[] LoanApplicationList_List)
        {
            this.LoanApplicationList_List = LoanApplicationList_List;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface LoanApplicationList_PortChannel : ServiceReference5.LoanApplicationList_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class LoanApplicationList_PortClient : System.ServiceModel.ClientBase<ServiceReference5.LoanApplicationList_Port>, ServiceReference5.LoanApplicationList_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LoanApplicationList_PortClient() : 
                base(LoanApplicationList_PortClient.GetDefaultBinding(), LoanApplicationList_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.LoanApplicationList_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoanApplicationList_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(LoanApplicationList_PortClient.GetBindingForEndpoint(endpointConfiguration), LoanApplicationList_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoanApplicationList_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LoanApplicationList_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoanApplicationList_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LoanApplicationList_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoanApplicationList_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference5.Read_Result ServiceReference5.LoanApplicationList_Port.Read(ServiceReference5.Read request)
        {
            return base.Channel.Read(request);
        }
        
        public ServiceReference5.LoanApplicationList Read(string Loan_No)
        {
            ServiceReference5.Read inValue = new ServiceReference5.Read();
            inValue.Loan_No = Loan_No;
            ServiceReference5.Read_Result retVal = ((ServiceReference5.LoanApplicationList_Port)(this)).Read(inValue);
            return retVal.LoanApplicationList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference5.Read_Result> ServiceReference5.LoanApplicationList_Port.ReadAsync(ServiceReference5.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference5.Read_Result> ReadAsync(string Loan_No)
        {
            ServiceReference5.Read inValue = new ServiceReference5.Read();
            inValue.Loan_No = Loan_No;
            return ((ServiceReference5.LoanApplicationList_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference5.ReadByRecId_Result ServiceReference5.LoanApplicationList_Port.ReadByRecId(ServiceReference5.ReadByRecId request)
        {
            return base.Channel.ReadByRecId(request);
        }
        
        public ServiceReference5.LoanApplicationList ReadByRecId(string recId)
        {
            ServiceReference5.ReadByRecId inValue = new ServiceReference5.ReadByRecId();
            inValue.recId = recId;
            ServiceReference5.ReadByRecId_Result retVal = ((ServiceReference5.LoanApplicationList_Port)(this)).ReadByRecId(inValue);
            return retVal.LoanApplicationList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference5.ReadByRecId_Result> ServiceReference5.LoanApplicationList_Port.ReadByRecIdAsync(ServiceReference5.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference5.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            ServiceReference5.ReadByRecId inValue = new ServiceReference5.ReadByRecId();
            inValue.recId = recId;
            return ((ServiceReference5.LoanApplicationList_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference5.ReadMultiple_Result ServiceReference5.LoanApplicationList_Port.ReadMultiple(ServiceReference5.ReadMultiple request)
        {
            return base.Channel.ReadMultiple(request);
        }
        
        public ServiceReference5.LoanApplicationList[] ReadMultiple(ServiceReference5.LoanApplicationList_Filter[] filter, string bookmarkKey, int setSize)
        {
            ServiceReference5.ReadMultiple inValue = new ServiceReference5.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            ServiceReference5.ReadMultiple_Result retVal = ((ServiceReference5.LoanApplicationList_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference5.ReadMultiple_Result> ServiceReference5.LoanApplicationList_Port.ReadMultipleAsync(ServiceReference5.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference5.ReadMultiple_Result> ReadMultipleAsync(ServiceReference5.LoanApplicationList_Filter[] filter, string bookmarkKey, int setSize)
        {
            ServiceReference5.ReadMultiple inValue = new ServiceReference5.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ServiceReference5.LoanApplicationList_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference5.IsUpdated_Result ServiceReference5.LoanApplicationList_Port.IsUpdated(ServiceReference5.IsUpdated request)
        {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key)
        {
            ServiceReference5.IsUpdated inValue = new ServiceReference5.IsUpdated();
            inValue.Key = Key;
            ServiceReference5.IsUpdated_Result retVal = ((ServiceReference5.LoanApplicationList_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference5.IsUpdated_Result> ServiceReference5.LoanApplicationList_Port.IsUpdatedAsync(ServiceReference5.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference5.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            ServiceReference5.IsUpdated inValue = new ServiceReference5.IsUpdated();
            inValue.Key = Key;
            return ((ServiceReference5.LoanApplicationList_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference5.GetRecIdFromKey_Result ServiceReference5.LoanApplicationList_Port.GetRecIdFromKey(ServiceReference5.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key)
        {
            ServiceReference5.GetRecIdFromKey inValue = new ServiceReference5.GetRecIdFromKey();
            inValue.Key = Key;
            ServiceReference5.GetRecIdFromKey_Result retVal = ((ServiceReference5.LoanApplicationList_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference5.GetRecIdFromKey_Result> ServiceReference5.LoanApplicationList_Port.GetRecIdFromKeyAsync(ServiceReference5.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference5.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            ServiceReference5.GetRecIdFromKey inValue = new ServiceReference5.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ServiceReference5.LoanApplicationList_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference5.Create_Result ServiceReference5.LoanApplicationList_Port.Create(ServiceReference5.Create request)
        {
            return base.Channel.Create(request);
        }
        
        public void Create(ref ServiceReference5.LoanApplicationList LoanApplicationList)
        {
            ServiceReference5.Create inValue = new ServiceReference5.Create();
            inValue.LoanApplicationList = LoanApplicationList;
            ServiceReference5.Create_Result retVal = ((ServiceReference5.LoanApplicationList_Port)(this)).Create(inValue);
            LoanApplicationList = retVal.LoanApplicationList;
        }
        
        public System.Threading.Tasks.Task<ServiceReference5.Create_Result> CreateAsync(ServiceReference5.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference5.CreateMultiple_Result ServiceReference5.LoanApplicationList_Port.CreateMultiple(ServiceReference5.CreateMultiple request)
        {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref ServiceReference5.LoanApplicationList[] LoanApplicationList_List)
        {
            ServiceReference5.CreateMultiple inValue = new ServiceReference5.CreateMultiple();
            inValue.LoanApplicationList_List = LoanApplicationList_List;
            ServiceReference5.CreateMultiple_Result retVal = ((ServiceReference5.LoanApplicationList_Port)(this)).CreateMultiple(inValue);
            LoanApplicationList_List = retVal.LoanApplicationList_List;
        }
        
        public System.Threading.Tasks.Task<ServiceReference5.CreateMultiple_Result> CreateMultipleAsync(ServiceReference5.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference5.Update_Result ServiceReference5.LoanApplicationList_Port.Update(ServiceReference5.Update request)
        {
            return base.Channel.Update(request);
        }
        
        public void Update(ref ServiceReference5.LoanApplicationList LoanApplicationList)
        {
            ServiceReference5.Update inValue = new ServiceReference5.Update();
            inValue.LoanApplicationList = LoanApplicationList;
            ServiceReference5.Update_Result retVal = ((ServiceReference5.LoanApplicationList_Port)(this)).Update(inValue);
            LoanApplicationList = retVal.LoanApplicationList;
        }
        
        public System.Threading.Tasks.Task<ServiceReference5.Update_Result> UpdateAsync(ServiceReference5.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference5.UpdateMultiple_Result ServiceReference5.LoanApplicationList_Port.UpdateMultiple(ServiceReference5.UpdateMultiple request)
        {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref ServiceReference5.LoanApplicationList[] LoanApplicationList_List)
        {
            ServiceReference5.UpdateMultiple inValue = new ServiceReference5.UpdateMultiple();
            inValue.LoanApplicationList_List = LoanApplicationList_List;
            ServiceReference5.UpdateMultiple_Result retVal = ((ServiceReference5.LoanApplicationList_Port)(this)).UpdateMultiple(inValue);
            LoanApplicationList_List = retVal.LoanApplicationList_List;
        }
        
        public System.Threading.Tasks.Task<ServiceReference5.UpdateMultiple_Result> UpdateMultipleAsync(ServiceReference5.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoanApplicationList_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoanApplicationList_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://ochiengowino:3332/CapitalSaccoInstance/WS/CAPITAL SACCO/Page/LoanApplicati" +
                        "onList");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LoanApplicationList_PortClient.GetBindingForEndpoint(EndpointConfiguration.LoanApplicationList_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LoanApplicationList_PortClient.GetEndpointAddress(EndpointConfiguration.LoanApplicationList_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            LoanApplicationList_Port,
        }
    }
}
