//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", ConfigurationName="ServiceReference1.MsaccoMobiAPI_Port")]
    public interface MsaccoMobiAPI_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/msaccomobiapi:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.Read_Result> ReadAsync(ServiceReference1.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/msaccomobiapi:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.ReadByRecId_Result> ReadByRecIdAsync(ServiceReference1.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/msaccomobiapi:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.ReadMultiple_Result> ReadMultipleAsync(ServiceReference1.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/msaccomobiapi:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.IsUpdated_Result> IsUpdatedAsync(ServiceReference1.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/msaccomobiapi:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ServiceReference1.GetRecIdFromKey request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/msaccomobiapi:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.Create_Result> CreateAsync(ServiceReference1.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/msaccomobiapi:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CreateMultiple_Result> CreateMultipleAsync(ServiceReference1.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/msaccomobiapi:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.Update_Result> UpdateAsync(ServiceReference1.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/msaccomobiapi:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.UpdateMultiple_Result> UpdateMultipleAsync(ServiceReference1.UpdateMultiple request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi")]
    public partial class MsaccoMobiAPI
    {
        
        private string keyField;
        
        private string noField;
        
        private System.DateTime document_DateField;
        
        private bool document_DateFieldSpecified;
        
        private Application_Type application_TypeField;
        
        private bool application_TypeFieldSpecified;
        
        private string member_NoField;
        
        private string initial_Application_NoField;
        
        private Verification_Document verification_DocumentField;
        
        private bool verification_DocumentFieldSpecified;
        
        private string verification_Doc_NoField;
        
        private string customer_NameField;
        
        private string mPESA_Mobile_NoField;
        
        private string commentsField;
        
        private System.DateTime date_EnteredField;
        
        private bool date_EnteredFieldSpecified;
        
        private string entered_ByField;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private string withdrawal_Limit_CodeField;
        
        private decimal withdrawal_Limit_AmountField;
        
        private bool withdrawal_Limit_AmountFieldSpecified;
        
        private string responsibility_CenterField;
        
        private string recIDField;
        
        private string transaction_TypeField;
        
        private string product_TypeField;
        
        private string billable_AccountField;
        
        private decimal billable_AmountField;
        
        private bool billable_AmountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime Document_Date
        {
            get
            {
                return this.document_DateField;
            }
            set
            {
                this.document_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_DateSpecified
        {
            get
            {
                return this.document_DateFieldSpecified;
            }
            set
            {
                this.document_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Application_Type Application_Type
        {
            get
            {
                return this.application_TypeField;
            }
            set
            {
                this.application_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Application_TypeSpecified
        {
            get
            {
                return this.application_TypeFieldSpecified;
            }
            set
            {
                this.application_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Member_No
        {
            get
            {
                return this.member_NoField;
            }
            set
            {
                this.member_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Initial_Application_No
        {
            get
            {
                return this.initial_Application_NoField;
            }
            set
            {
                this.initial_Application_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Verification_Document Verification_Document
        {
            get
            {
                return this.verification_DocumentField;
            }
            set
            {
                this.verification_DocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Verification_DocumentSpecified
        {
            get
            {
                return this.verification_DocumentFieldSpecified;
            }
            set
            {
                this.verification_DocumentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Verification_Doc_No
        {
            get
            {
                return this.verification_Doc_NoField;
            }
            set
            {
                this.verification_Doc_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Customer_Name
        {
            get
            {
                return this.customer_NameField;
            }
            set
            {
                this.customer_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MPESA_Mobile_No
        {
            get
            {
                return this.mPESA_Mobile_NoField;
            }
            set
            {
                this.mPESA_Mobile_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime Date_Entered
        {
            get
            {
                return this.date_EnteredField;
            }
            set
            {
                this.date_EnteredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Date_EnteredSpecified
        {
            get
            {
                return this.date_EnteredFieldSpecified;
            }
            set
            {
                this.date_EnteredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Entered_By
        {
            get
            {
                return this.entered_ByField;
            }
            set
            {
                this.entered_ByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Withdrawal_Limit_Code
        {
            get
            {
                return this.withdrawal_Limit_CodeField;
            }
            set
            {
                this.withdrawal_Limit_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal Withdrawal_Limit_Amount
        {
            get
            {
                return this.withdrawal_Limit_AmountField;
            }
            set
            {
                this.withdrawal_Limit_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Withdrawal_Limit_AmountSpecified
        {
            get
            {
                return this.withdrawal_Limit_AmountFieldSpecified;
            }
            set
            {
                this.withdrawal_Limit_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Responsibility_Center
        {
            get
            {
                return this.responsibility_CenterField;
            }
            set
            {
                this.responsibility_CenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string RecID
        {
            get
            {
                return this.recIDField;
            }
            set
            {
                this.recIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Transaction_Type
        {
            get
            {
                return this.transaction_TypeField;
            }
            set
            {
                this.transaction_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Product_Type
        {
            get
            {
                return this.product_TypeField;
            }
            set
            {
                this.product_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Billable_Account
        {
            get
            {
                return this.billable_AccountField;
            }
            set
            {
                this.billable_AccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal Billable_Amount
        {
            get
            {
                return this.billable_AmountField;
            }
            set
            {
                this.billable_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Billable_AmountSpecified
        {
            get
            {
                return this.billable_AmountFieldSpecified;
            }
            set
            {
                this.billable_AmountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi")]
    public enum Application_Type
    {
        
        /// <remarks/>
        Initial,
        
        /// <remarks/>
        Deactivate,
        
        /// <remarks/>
        PIN_Change,
        
        /// <remarks/>
        Suspend,
        
        /// <remarks/>
        Activate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi")]
    public enum Verification_Document
    {
        
        /// <remarks/>
        National_ID,
        
        /// <remarks/>
        Passport,
        
        /// <remarks/>
        Military_ID,
        
        /// <remarks/>
        Diplomatic_ID,
        
        /// <remarks/>
        Alien_ID,
        
        /// <remarks/>
        Drivers_Licence,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi")]
    public enum Status
    {
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Rejected,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi")]
    public partial class MsaccoMobiAPI_Filter
    {
        
        private MsaccoMobiAPI_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MsaccoMobiAPI_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi")]
    public enum MsaccoMobiAPI_Fields
    {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Document_Date,
        
        /// <remarks/>
        Application_Type,
        
        /// <remarks/>
        Member_No,
        
        /// <remarks/>
        Initial_Application_No,
        
        /// <remarks/>
        Verification_Document,
        
        /// <remarks/>
        Verification_Doc_No,
        
        /// <remarks/>
        Customer_Name,
        
        /// <remarks/>
        MPESA_Mobile_No,
        
        /// <remarks/>
        Comments,
        
        /// <remarks/>
        Date_Entered,
        
        /// <remarks/>
        Entered_By,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Withdrawal_Limit_Code,
        
        /// <remarks/>
        Withdrawal_Limit_Amount,
        
        /// <remarks/>
        Responsibility_Center,
        
        /// <remarks/>
        RecID,
        
        /// <remarks/>
        Transaction_Type,
        
        /// <remarks/>
        Product_Type,
        
        /// <remarks/>
        Billable_Account,
        
        /// <remarks/>
        Billable_Amount,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        public string No;
        
        public Read()
        {
        }
        
        public Read(string No)
        {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        public ServiceReference1.MsaccoMobiAPI MsaccoMobiAPI;
        
        public Read_Result()
        {
        }
        
        public Read_Result(ServiceReference1.MsaccoMobiAPI MsaccoMobiAPI)
        {
            this.MsaccoMobiAPI = MsaccoMobiAPI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        public ServiceReference1.MsaccoMobiAPI MsaccoMobiAPI;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(ServiceReference1.MsaccoMobiAPI MsaccoMobiAPI)
        {
            this.MsaccoMobiAPI = MsaccoMobiAPI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ServiceReference1.MsaccoMobiAPI_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(ServiceReference1.MsaccoMobiAPI_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference1.MsaccoMobiAPI[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(ServiceReference1.MsaccoMobiAPI[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        public ServiceReference1.MsaccoMobiAPI MsaccoMobiAPI;
        
        public Create()
        {
        }
        
        public Create(ServiceReference1.MsaccoMobiAPI MsaccoMobiAPI)
        {
            this.MsaccoMobiAPI = MsaccoMobiAPI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        public ServiceReference1.MsaccoMobiAPI MsaccoMobiAPI;
        
        public Create_Result()
        {
        }
        
        public Create_Result(ServiceReference1.MsaccoMobiAPI MsaccoMobiAPI)
        {
            this.MsaccoMobiAPI = MsaccoMobiAPI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference1.MsaccoMobiAPI[] MsaccoMobiAPI_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(ServiceReference1.MsaccoMobiAPI[] MsaccoMobiAPI_List)
        {
            this.MsaccoMobiAPI_List = MsaccoMobiAPI_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference1.MsaccoMobiAPI[] MsaccoMobiAPI_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(ServiceReference1.MsaccoMobiAPI[] MsaccoMobiAPI_List)
        {
            this.MsaccoMobiAPI_List = MsaccoMobiAPI_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        public ServiceReference1.MsaccoMobiAPI MsaccoMobiAPI;
        
        public Update()
        {
        }
        
        public Update(ServiceReference1.MsaccoMobiAPI MsaccoMobiAPI)
        {
            this.MsaccoMobiAPI = MsaccoMobiAPI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        public ServiceReference1.MsaccoMobiAPI MsaccoMobiAPI;
        
        public Update_Result()
        {
        }
        
        public Update_Result(ServiceReference1.MsaccoMobiAPI MsaccoMobiAPI)
        {
            this.MsaccoMobiAPI = MsaccoMobiAPI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference1.MsaccoMobiAPI[] MsaccoMobiAPI_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(ServiceReference1.MsaccoMobiAPI[] MsaccoMobiAPI_List)
        {
            this.MsaccoMobiAPI_List = MsaccoMobiAPI_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/msaccomobiapi", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference1.MsaccoMobiAPI[] MsaccoMobiAPI_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(ServiceReference1.MsaccoMobiAPI[] MsaccoMobiAPI_List)
        {
            this.MsaccoMobiAPI_List = MsaccoMobiAPI_List;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface MsaccoMobiAPI_PortChannel : ServiceReference1.MsaccoMobiAPI_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class MsaccoMobiAPI_PortClient : System.ServiceModel.ClientBase<ServiceReference1.MsaccoMobiAPI_Port>, ServiceReference1.MsaccoMobiAPI_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MsaccoMobiAPI_PortClient() : 
                base(MsaccoMobiAPI_PortClient.GetDefaultBinding(), MsaccoMobiAPI_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MsaccoMobiAPI_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MsaccoMobiAPI_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(MsaccoMobiAPI_PortClient.GetBindingForEndpoint(endpointConfiguration), MsaccoMobiAPI_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MsaccoMobiAPI_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MsaccoMobiAPI_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MsaccoMobiAPI_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MsaccoMobiAPI_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MsaccoMobiAPI_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Read_Result> ServiceReference1.MsaccoMobiAPI_Port.ReadAsync(ServiceReference1.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Read_Result> ReadAsync(string No)
        {
            ServiceReference1.Read inValue = new ServiceReference1.Read();
            inValue.No = No;
            return ((ServiceReference1.MsaccoMobiAPI_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ReadByRecId_Result> ServiceReference1.MsaccoMobiAPI_Port.ReadByRecIdAsync(ServiceReference1.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            ServiceReference1.ReadByRecId inValue = new ServiceReference1.ReadByRecId();
            inValue.recId = recId;
            return ((ServiceReference1.MsaccoMobiAPI_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ReadMultiple_Result> ServiceReference1.MsaccoMobiAPI_Port.ReadMultipleAsync(ServiceReference1.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ReadMultiple_Result> ReadMultipleAsync(ServiceReference1.MsaccoMobiAPI_Filter[] filter, string bookmarkKey, int setSize)
        {
            ServiceReference1.ReadMultiple inValue = new ServiceReference1.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ServiceReference1.MsaccoMobiAPI_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.IsUpdated_Result> ServiceReference1.MsaccoMobiAPI_Port.IsUpdatedAsync(ServiceReference1.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            ServiceReference1.IsUpdated inValue = new ServiceReference1.IsUpdated();
            inValue.Key = Key;
            return ((ServiceReference1.MsaccoMobiAPI_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetRecIdFromKey_Result> ServiceReference1.MsaccoMobiAPI_Port.GetRecIdFromKeyAsync(ServiceReference1.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            ServiceReference1.GetRecIdFromKey inValue = new ServiceReference1.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ServiceReference1.MsaccoMobiAPI_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Create_Result> CreateAsync(ServiceReference1.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreateMultiple_Result> CreateMultipleAsync(ServiceReference1.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Update_Result> UpdateAsync(ServiceReference1.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.UpdateMultiple_Result> UpdateMultipleAsync(ServiceReference1.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MsaccoMobiAPI_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MsaccoMobiAPI_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://ochiengowino:3332/CapitalSaccoInstance/WS/CAPITAL SACCO/Page/MsaccoMobiAPI" +
                        "");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MsaccoMobiAPI_PortClient.GetBindingForEndpoint(EndpointConfiguration.MsaccoMobiAPI_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MsaccoMobiAPI_PortClient.GetEndpointAddress(EndpointConfiguration.MsaccoMobiAPI_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            MsaccoMobiAPI_Port,
        }
    }
}
